### ISSUE TITLE
MANAGE USER

### ISSUE THREAD

**Issue by antonfx** [xtianfelix/ShowRoom#8]
![screen shot 2016-06-01 at 10 26 00 am](https://cloud.githubusercontent.com/assets/19643614/15697331/54d9f3a4-27e3-11e6-9823-6877a7245f4b.jpg)

Ooh ya di manage user tidak bisa lihat pasword nya apa ya.. 
jd kk sering lupa, langsung ketik pasw baru aja.. memang dibuat begitu ta?

**Comment by xtianfelix** [comment]
emang gitu
cm bisa reset password
